<KATALOG>
<KİTAP1>
<BASLIK>SUÇ VE CEZA </BASLIK>
<YAZAR>FYODOR DOSTOYEVSKİ</YAZAR>
<BASKIYILI>2009</BASKIYILI>
<BASKISAYISI>107</BASKISAYISI>
<UCRET>15.00</UCRET>
<DIL>TUR</DIL>

<KİTAP2>
<BAŞLIK>Yaşar ne yaşar ne yaşamaz</BASLIK>
<YAZAR>Aziz Nesin </YAZAR>
<BASKIYILI>2015</BASKIYILI>
<BASKISAYISI>Yirmi Beş</BASKISAYISI>
<UCRET>14.00</UCRET>
<DIL>TR</DIL>

<KİTAP3>
<BASLIK>Ana</BASLIK>
<YAZAR>Maksim Gorki</YAZAR>
<BASKIYILI>2005</BASKIYILI>
<BASKISAYISI>Altıncı basım</BASKISAYISI>
<UCRET>12.50</UCRET>
<DIL>Tur</DIL>

<KİTAP4>
<BASLIK>Dijital Kale </BASLIK>
<YAZAR>Dan Brown </YAZAR>
<BASKIYILI>2003</BASKIYILI>
<BASKISAYISI>13. baskı</BASKISAYISI>
<UCRET>17.50</UCRET>
<DIL>ING</DIL>

<FILM1>
<BASLIK>Forrest Gump </BASLIK>
<YONETMEN>Robert Zemeckıs </YONETMEN>
<YILI>1994</YILI>
<SENARYO >Wınston Groom </SENARYO>
<ULKE>USA</ULKE>
<DIL>ING</DIL>
